#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore
${HOME}/.config/polybar/launch.sh
picom --experimental-backends &

bspc monitor DisplayPort-0 -d 1 2 3 4 
bspc monitor DisplayPort-1 -d 5 6 7 8 

bspc config border_width         2
bspc config window_gap          12
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
bspc config pointer_follows_focus false


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Yubico Authenticator" desktop='^3' state=floating follow=on
bspc rule -a Galculator desktop='^3' state=floating follow=on
bspc rule -a Geany desktop='^5' follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Thunar desktop='^7' follow=on

